### ISSUE TITLE
Installation is incomplete. Check the console log for errors before trying again. 

### ISSUE THREAD

**Issue by mengbo123456** [mengbo123456/mengbo#1]
![image](https://user-images.githubusercontent.com/29748690/27625634-d6b6fdcc-5c17-11e7-94b4-352d7fbf4c12.png)

[ERROR] exception 'LogicException' with message 'Unknown module in the requested list: 'Magento_BundleSampleData'' in C:\inetpub\wwwroot\Magento02\setup\src\Magento\Setup\Model\Installer.php:431 Stack trace: #0 C:\inetpub\wwwroot\Magento02\setup\src\Magento\Setup\Model\Installer.php(390): Magento\Setup\Model\Installer->readListOfModules(Array, Array, 'enable_modules') #1 C:\inetpub\wwwroot\Magento02\setup\src\Magento\Setup\Model\Installer.php(336): Magento\Setup\Model\Installer->createModulesConfig(Array, true) #2 C:\inetpub\wwwroot\Magento02\setup\src\Magento\Setup\Controller\Install.php(109): Magento\Setup\Model\Installer->install(Array) #3 C:\inetpub\wwwroot\Magento02\vendor\zendframework\zend-mvc\src\Controller\AbstractActionController.php(82): Magento\Setup\Controller\Install->startAction() #4 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent)) #5 C:\inetpub\wwwroot\Magento02\vendor\zendframework\zend-eventmanager\src\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #6 C:\inetpub\wwwroot\Magento02\vendor\zendframework\zend-eventmanager\src\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #7 C:\inetpub\wwwroot\Magento02\vendor\zendframework\zend-mvc\src\Controller\AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #8 C:\inetpub\wwwroot\Magento02\vendor\zendframework\zend-mvc\src\DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response)) #9 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent)) #10 C:\inetpub\wwwroot\Magento02\vendor\zendframework\zend-eventmanager\src\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #11 C:\inetpub\wwwroot\Magento02\vendor\zendframework\zend-eventmanager\src\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #12 C:\inetpub\wwwroot\Magento02\vendor\zendframework\zend-mvc\src\Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #13 C:\inetpub\wwwroot\Magento02\setup\index.php(31): Zend\Mvc\Application->run() #14 {main}

**Comment by mengbo123456** [comment]
![image](https://user-images.githubusercontent.com/29748690/27625587-b506efa2-5c17-11e7-95ff-0a6725322c73.png)

**Comment by mengbo123456** [comment]
found answer

![qq 20170628190654](https://user-images.githubusercontent.com/29748690/27634208-01354078-5c35-11e7-88cc-f4ea30cea26f.png)


here php only current version
